name: Sync v2rayNG
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  process-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone v2rayNG (仅最新提交)
        uses: actions/checkout@v4
        with:
          repository: 2dust/v2rayNG
          path: v2rayNG
          fetch-depth: 1  # 仅拉取最新提交

      - name: Analyze Commits
        run: |
          cd v2rayNG
          git log --pretty=format:"%h|%an|%ad|%s" > commits.log
          python ../scripts/process_logs.py  # 确保脚本路径正确
        working-directory: ${{ github.workspace }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "更新v2rayNG日志分析"
          file_pattern: |
            v2rayNG/commits.log
            logs/*
