name: Sync v2rayNG
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  process-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: rm -rf ./target-repo  # 清理残留目录

      - name: Clone v2rayNG (master分支)
        uses: actions/checkout@v4
        with:
          repository: 2dust/v2rayNG
          path: target-repo
          fetch-depth: 1
          ref: master  # 关键修复点

      - name: Verify Script Exists
        run: |
          if [ ! -f "target-repo/scripts/process_logs.py" ]; then
            echo "错误：脚本不存在于 target-repo/scripts/"
            exit 1
          fi

      - name: Analyze Commits
        run: |
          cd target-repo
          git log --pretty=format:"%h|%an|%ad|%s" > commits.log
          python scripts/process_logs.py

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "更新v2rayNG日志分析"
          file_pattern: |
            target-repo/commits.log
            logs/*
