name: CI
on:
  schedule:
    - cron: '0 14 * * *'  # 保持原有定时触发
  workflow_dispatch:

jobs:
  process-v2rayng-logs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Clone v2rayNG
      run: |
        git clone --depth 1 https://github.com/2dust/v2rayNG.git
        cd v2rayNG
        git log --pretty=format:"%h|%an|%ad|%s" > ../commits.log
      working-directory: ${{ github.workspace }}

    - name: Process Logs
      run: |
        python scripts/process_v2rayng_logs.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "更新v2rayNG日志分析"
        file_pattern: |
          README.md
          logs/v2rayng_commits.json
