name: Clone v2rayNG
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 14 * * *'  # 可选定时触发

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: 清理工作区
        run: rm -rf v2rayNG  # 避免残留文件冲突

      - name: 克隆 v2rayNG (master分支)
        uses: actions/checkout@v4
        with:
          repository: 2dust/v2rayNG
          path: v2rayNG  # 指定克隆到独立目录
          ref: master    # 明确指定分支
          fetch-depth: 1 # 仅克隆最新提交

      - name: 验证克隆结果
        run: |
          echo "仓库目录结构："
          ls -al v2rayNG  # 输出克隆后的目录内容
