name: Sync v2rayNG
on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  process-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone v2rayNG (仅最新提交)
        uses: actions/checkout@v4
        with:
          repository: 2dust/v2rayNG
          path: target-repo  # 独立路径
          fetch-depth: 1

      - name: Analyze Commits
        run: |
          cd target-repo
          git log --pretty=format:"%h|%an|%ad|%s" > commits.log
          python scripts/process_logs.py  # 直接调用仓库内的脚本
        working-directory: ${{ github.workspace }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "更新v2rayNG日志分析"
          file_pattern: |
            target-repo/commits.log
            logs/*
