name: Verified Clone

on:
  workflow_dispatch:

jobs:
  debug_clone:
    runs-on: ubuntu-latest
    steps:
      - name: 基础克隆（带详细日志）
        uses: actions/checkout@v4
        with:
          repository: harry0703/MoneyPrinterTurbo
          path: ./cloned-repo
          fetch-depth: 1
          lfs: true  # 如果仓库包含 LFS 内容

      - name: 显示系统信息
        run: |
          echo "GitHub Workspace: ${{ github.workspace }}"
          echo "Current Directory: $(pwd)"
          ls -la

      - name: 验证克隆内容
        run: |
          if [ -z "$(ls -A ./cloned-repo)" ]; then
            echo "::error::克隆目录为空！"
            exit 1
          fi
          echo "找到 $(find ./cloned-repo -type f | wc -l) 个文件"

      - name: 显示最新提交
        run: |
          git -C ./cloned-repo log -1 --pretty="%H %s"

      - name: 尝试编译（示例操作）
        run: |
          cd ./cloned-repo
          npm install  # 根据实际项目调整
          npm run build
