# 文件名：.github/workflows/sync-beta.yml
name: Sync Latest v2rayNG Beta

on:
  schedule:
    # 每天UTC时间0点执行（北京时间8点）
    - cron: '0 0 * * *'
  workflow_dispatch:
    # 允许手动触发
    inputs:
      force_sync:
        description: '强制同步（即使无新版本）'
        required: false
        default: 'false'

permissions:
  contents: write  # 需要写入权限

jobs:
  sync-beta:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        # 配置为你的目标仓库（默认当前仓库）
        repository: ${{ github.repository }}
        token: ${{ secrets.SYNC_TOKEN }}
        path: target

    - name: Checkout source repo
      uses: actions/checkout@v4
      with:
        repository: 2dust/v2rayNG
        ref: beta  # 同步beta分支
        path: source
        token: ${{ secrets.SYNC_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Sync Branches
      run: |
        cd target
        # 添加源仓库为远程源
        git remote add source ../source/.git
        # 获取最新提交
        git fetch source
        # 强制同步beta分支
        git checkout -B beta source/beta
        # 推送到目标仓库
        git push --force origin beta

    - name: Create Sync Commit
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force_sync == 'true' }}
      run: |
        cd target
        git add .
        git commit -m "chore: force sync beta version" || exit 0
        git push origin beta
