name: Auto Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          repository: harry0703/MoneyPrinterTurbo
          token: ${{ secrets.SYNC_TOKEN }}
          path: ./app
          fetch-depth: 0

      - name: 更新版本号（示例操作）
        run: |
          cd ./app
          echo "AUTO_UPDATE_TIME=$(date +%s)" > version.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "chore: auto update version [skip ci]"

      # 关键修改：移除 --force 参数
      - name: 推送代码到 main
        run: |
          cd ./app
          git push origin main
