name: Auto Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 克隆代码库
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          repository: harry0703/MoneyPrinterTurbo
          token: ${{ secrets.SYNC_TOKEN }}
          path: ./app
          fetch-depth: 0

      # 2. 安装依赖（示例）
      - name: 安装 Node.js 依赖
        run: |
          cd ./app
          npm install

      # 3. 修改代码（示例：自动更新版本号）
      - name: 更新版本号
        run: |
          cd ./app
          echo "AUTO_UPDATE_TIME=$(date +%s)" > version.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add version.txt
          git commit -m "chore: auto update version [skip ci]"

      # 4. 推送到目标仓库
      - name: 强制推送代码
        run: |
          cd ./app
          git push origin main --force

      # 5. 触发部署（示例：SSH 到服务器）
      - name: 远程部署
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/myapp
            git pull origin main
            docker-compose restart
